# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6ed325527a9e5f3bd2ddac19dcc87e41f7f4801f1031fa4324e0fd57be7a51a65494f0c22e68dace8324e850d687f25e3587093cb3baddd1c08bc6af33b535e

test:
  secret_key_base: 8bc8fea7b532736d2f86d17f57623cec52449869cef01a3ffcc708d4ab24302a41f718638387ca86ba5c1e892cb11bb83ca6749f7c4cd572a6c698469936fb37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
